### ISSUE TITLE
Prevent error on empty feed

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Feedr#1]
Currently the feed throws up when emtpy:

> <b>Fatal error</b>:  Call to a member function format() on a non-object in <b>/srv/www/Feedr/templates/feed.pxml</b> on line <b>6</b><br />

**Comment by PeeHaa** [comment]
Do the other properties throw errors or was this the only case?

**Comment by HassanAlthaf** [comment]
@PeeHaa only the empty.
